def getChampionName(champion_id):
    if champion_id == 1:    return "Annie";
    elif champion_id == 2:    return "Olaf";
    elif champion_id == 3:    return "Galio";
    elif champion_id == 4:    return "Twisted Fate";
    elif champion_id == 5:    return "Xin Zhao";
    elif champion_id == 6:    return "Urgot";
    elif champion_id == 7:    return "LeBlanc";
    elif champion_id == 8:    return "Vladimir";
    elif champion_id == 9:    return "Fiddlesticks";
    elif champion_id == 10:    return "Kayle";
    elif champion_id == 11:    return "Master Yi";
    elif champion_id == 12:    return "Alistar";
    elif champion_id == 13:    return "Ryze";
    elif champion_id == 14:    return "Sion";
    elif champion_id == 15:    return "Sivir";
    elif champion_id == 16:    return "Soraka";
    elif champion_id == 17:    return "Teemo";
    elif champion_id == 18:    return "Tristana";
    elif champion_id == 19:    return "Warwick";
    elif champion_id == 20:    return "Nunu";
    elif champion_id == 21:    return "Miss Fortune";
    elif champion_id == 22:    return "Ashe";
    elif champion_id == 23:    return "Tryndamere";
    elif champion_id == 24:    return "Jax";
    elif champion_id == 25:    return "Morgana";
    elif champion_id == 26:    return "Zilean";
    elif champion_id == 27:    return "Singed";
    elif champion_id == 28:    return "Evelynn";
    elif champion_id == 29:    return "Twitch";
    elif champion_id == 30:    return "Karthus";
    elif champion_id == 31:    return "Cho'Gath";
    elif champion_id == 32:    return "Amumu";
    elif champion_id == 33:    return "Rammus";
    elif champion_id == 34:    return "Anivia";
    elif champion_id == 35:    return "Shaco";
    elif champion_id == 36:    return "Dr. Mundo";
    elif champion_id == 37:    return "Sona";
    elif champion_id == 38:    return "Kassadin";
    elif champion_id == 39:    return "Irelia";
    elif champion_id == 40:    return "Janna";
    elif champion_id == 41:    return "Gangplank";
    elif champion_id == 42:    return "Corki";
    elif champion_id == 43:    return "Karma";
    elif champion_id == 44:    return "Taric";
    elif champion_id == 45:    return "Veigar";
    elif champion_id == 48:    return "Trundle";
    elif champion_id == 50:    return "Swain";
    elif champion_id == 51:    return "Caitlyn";
    elif champion_id == 53:    return "Blitzcrank";
    elif champion_id == 54:    return "Malphite";
    elif champion_id == 55:    return "Katarina";
    elif champion_id == 56:    return "Nocturne";
    elif champion_id == 57:    return "Maokai";
    elif champion_id == 58:    return "Renekton";
    elif champion_id == 59:    return "Jarvan IV";
    elif champion_id == 61:    return "Orianna";
    elif champion_id == 62:    return "Wukong";
    elif champion_id == 63:    return "Brand";
    elif champion_id == 64:    return "Lee Sin";
    elif champion_id == 67:    return "Vayne";
    elif champion_id == 68:    return "Rumble";
    elif champion_id == 69:    return "Cassiopeia";
    elif champion_id == 72:    return "Skarner";
    elif champion_id == 74:    return "Heimerdinger";
    elif champion_id == 75:    return "Nasus";
    elif champion_id == 76:    return "Nidalee";
    elif champion_id == 77:    return "Udyr";
    elif champion_id == 78:    return "Poppy";
    elif champion_id == 79:    return "Gragas";
    elif champion_id == 80:    return "Pantheon";
    elif champion_id == 81:    return "Ezreal";
    elif champion_id == 82:    return "Mordekaiser";
    elif champion_id == 83:    return "Yorick";
    elif champion_id == 84:    return "Akali";
    elif champion_id == 85:    return "Kennen";
    elif champion_id == 86:    return "Garen";
    elif champion_id == 89:    return "Leona";
    elif champion_id == 90:    return "Malzahar";
    elif champion_id == 91:    return "Talon";
    elif champion_id == 92:    return "Riven";
    elif champion_id == 96:    return "Kog'Maw";
    elif champion_id == 98:    return "Shen";
    elif champion_id == 99:    return "Lux";
    elif champion_id == 101:    return "Xerath";
    elif champion_id == 102:    return "Shyvana";
    elif champion_id == 103:    return "Ahri";
    elif champion_id == 104:    return "Graves";
    elif champion_id == 105:    return "Fizz";
    elif champion_id == 106:    return "Volibear";
    elif champion_id == 107:    return "Rengar";
    elif champion_id == 110:    return "Varus";
    elif champion_id == 111:    return "Nautilus";
    elif champion_id == 112:    return "Viktor";
    elif champion_id == 113:    return "Sejuani";
    elif champion_id == 114:    return "Fiora";
    elif champion_id == 115:    return "Ziggs";
    elif champion_id == 117:    return "Lulu";
    elif champion_id == 119:    return "Draven";
    elif champion_id == 120:    return "Hecarim";
    elif champion_id == 122:    return "Darius";
    elif champion_id == 126:    return "Jayce";
    elif champion_id == 131:    return "Diana";
    elif champion_id == 143:    return "Zyra";
    elif champion_id == 517:    return "Sylas";
    else:
        return "Unknwon"